@startuml

class Facade {
    + doSomething()
}

together {
    package package1 {
        class Class1 {
        }
    }

    package package2 {
        class Class2 {
        }
    }

    package package3 {
        class Class3 {
        }
    }
}

Facade ..> package1 : <<include>>
Facade ..> package2 : <<include>>
Facade ..> package3 : <<include>>

Client1 ..> Facade : doSomething()
Client2 ..> Facade : doSomething()

together {
    class Client1 {
    }

    class Client2 {
    }
}

note left of Facade::"doSomething()"
    Class1 class1 = new Class1();
    Class2 class2 = new Class2();
    Class3 class3 = new Class3();

    class1.doStuff(class2);
    // ...
end note

@enduml
