@startuml

together {
    interface AbstractProductA {
    }

    class ProductA1 {
    }
}

together {
    interface AbstractProductB {
    }

    class ProductB1 {
    }
}

together {
    interface AbstractFactory {
        + createProductA() : ProductA
        + createProductB() : ProductB
    }

    class Factory1 {
        + createProductA() : ProductA
        + createProductB() : ProductB
    }
}

class Client {
}

ProductA1 ..|> AbstractProductA
ProductB1 ..|> AbstractProductB
Factory1 ..|> AbstractFactory

Client ..> AbstractFactory : <<use>>
Client ..> AbstractProductA : <<use>>
Client ..> AbstractProductB : <<use>>

Factory1 ..> ProductA1 : <<create>>
Factory1 ..> ProductB1 : <<create>>

@enduml
