@startuml

class Context {
}

interface Expression {
    + interpret(context : Context)
}

class TerminalExpression {
    + interpret(context : Context)
}

class NonTerminalExpression {
    - expressions : Expression
    + interpret(context : Context)
}

class Client {
}

TerminalExpression ..|> Expression
NonTerminalExpression ..|> Expression
Expression "-expression" ..o NonTerminalExpression
Client ..> Expression
Client ..> Context

note left of Context
    包含解释器之外的一些全局信息。
end note

note left of Client
     调用解释操作。
end note

@enduml
