@startuml

abstract class Handler {
    - successor : Handler
    + handleRequest() {abstract}
}

class ConcreteHandler {
    + handleRequest()
}

class Client {
}

ConcreteHandler ..|> Handler
Handler "-successor" --o Handler
Client ..> Handler : <<use>>

note left of ConcreteHandler::"handleRequest()"
    if can handle {
        handleRequest()
    } else {
        successor.handleRequest()
    }
end note

note right of Client
    handler.handleRequest()
end note

@enduml
