@startuml

class Product {
}

interface Builder {
    + buildPartA()
    + buildPartB()
}

class ConcreteBuilder {
    + buildPartA()
    + buildPartB()
    + getResult() : Product
}

class Director {
    - builder : Builder
    + construct() : void
}

class Client {
}

ConcreteBuilder ..|> Builder
Builder "-builder" --o Director
ConcreteBuilder ..> Product : <<create>>
Client ..> Director : <<use>>

note left of Director::"construct()"
    builder.buildPartA()
    builder.buildPartB()
end note

note left of Client
    ConcreteBuilder concreteBuilder = new ConcreteBuilder();
    Director director = new Director(concreteBuilder);
    director.construct();
    Product product = concreteBuilder.getResult();
end note

@enduml
