@startuml

class Target {
    + request()
}

class ConcreteTarget {
}

class Adapter {
    + request()
}

class Adaptee {
    + specificRequest()
}

ConcreteTarget --|> Target
Adapter --|> Target : private
Adapter --|> Adaptee : public

note left of Adapter::"request()"
    adaptee.specificRequest();
end note

note as N1
    Adaptee 与 Target 相似，只是有几个接口不同。
    可用 Adaptee 充当 Target 的子类。Adapter 就是转接器，使 Adaptee “变成” Target 的类型。
end note

@enduml
